name: Compile & Release

on:
  push:
    branches:
      - master
      - chore/setup-actions

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          compiler: pdflatex

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest CV Release
          body: "Generated CV from the latest commit."
          files: main.pdf
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
